# Generated by Django 3.1.7 on 2021-02-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='subject',
            field=models.TextField(),
        ),
    ]
